### ISSUE TITLE
Workflow with binder

### ISSUE THREAD

**Issue by matthewjhenry** [hdrake/cmip6-temperature-demo#3]
Hi,

I am very new to this pangeo binder stuff. I managed to modify the file for my research purposes, but I am confused about the workflow.

I just downloaded the modified notebook and uploaded it into a new github repo. Is there a way to commit the changes to the notebook directly from the binder?

Also, I generated new plots from cmip6 and would like to export this small amount of data back to my home computer. I don't see an obvious way of doing this.

Cheers,

-Matthew

**Comment by hdrake** [comment]
My impression is that the recommended workflow is not to do any permanent work in a binder; binder instances are meant for demos and tutorials of permanent code, such that any modifications of the code within the binder instance are evanescent. Instead, the recommended workflow is to fork the full repository, clone it locally, make your edits, and push them back to the forked github repository to back them up. If you generate any figures or small derived datasets (less than a few hundred Mb so it is conveniently managed by git), you just commit and push those to github so you can easily download them locally back on your laptop.

I recommend doing all of this via a JupyterHub on the Google Cloud (and just leverage the cloud-hosted data and utilities), for example by using the Pangeo resource https://ocean.pangeo.io/ (you just need an OrcidID to log in). The JupyterLab instance will let you easily spin off either terminal instances (for git commands) and Jupyter Notebooks (for running the analysis code).

Let me know if that makes sense and good luck!

**Comment by hdrake** [comment]
@aedessler, you may also find this Issue useful.
